components:
  schemas:
    LoginBody:
      type: object
      properties:
        email:
          type: string
          example: tam.socket.test@gmail.com
        password:
          type: string
          example: Duoc123!
    SuccessAuthentication:
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjc3ZmZlYTQ5MmRhMmYwNWVhYWI5ZjI2IiwidG9rZW5fdHlwZSI6MCwidmVyaWZ5IjoxLCJpYXQiOjE3MzcxMzE4OTUsImV4cCI6MTc0NTc3MTg5NX0.7ZZ7kjIA4k55UfHlv9POINgtgvL0nfhw85W_h30pA00
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjc3ZmZlYTQ5MmRhMmYwNWVhYWI5ZjI2IiwidG9rZW5fdHlwZSI6MSwidmVyaWZ5IjoxLCJpYXQiOjE3MzcxMzE4OTUsImV4cCI6MTc0NTc3MTg5NX0.kJOa2CTiBuq1Hd3DJZGDSmR6vMD7brp--eJXmelq4ik
    User:
      type: object
      properties:
        _id:
          type: string
          format: MongoId
          example: 677ffea492da2f05eaab9f26
        name:
          type: string
          example: tam
        email:
          type: string
          example: tam.socket.test@gmail.com
        date_of_birth:
          type: string
          format: ISO8601
          example: 2000-11-18T12:53:09.553Z
        created_at:
          type: string
          format: ISO8601
          example: 2025-01-09T16:51:48.966Z
        updated_at:
          type: string
          format: ISO8601
          example: 2025-01-09T16:54:53.187Z
        verify:
          $ref: '#/components/schemas/UserVerifyStatus'
        twitter_circle:
          type: array
          items:
            type: string
            format: MongoId
          example: ['677ffea492da2f05eaab9f26', '677ffea492da2f05eaab9f2c']
        bio:
          type: string
          example: 'This is my bio'
        location:
          type: string
          example: 'Los Angeles, LA'
        website:
          type: string
          example: 'www.example.com'
        username:
          type: string
          example: 'user_677ffea492da2f05eaab9f26'
        avatar:
          type: string
          example: 'http://localhost:4000/images/avatars/johndoe.jpg'
        cover_photo:
          type: string
          example: 'http://localhost:4000/images/avatars/johndoe.jpg'
    UserVerifyStatus:
      type: number
      enum: [Unverified, Verified, Banned]
      example: 1
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
